[package]
name = "axum_query_filters"
version = "0.0.0"
license = "MIT"
authors = ["Ruslan Ivlev <tokyo-jager@yadex.ru>"]
description = "desc"
edition = "2021"

[dependencies]
axum = "0.7.5"

[lib]
name ="axum_query_filters"
path = "src/lib.rs"

